# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  - name: AppServiceName
    type: string
    default: 'certificate-pdf'
    values:
      - 'certificate-pdf'
      - 'ext-user-service'
      - 'vessel-service'
      - 'workorder-service'
      
  - name: Environment
    type: string
    default: 'BuildandDeploy'
    values:
      - 'BuildandDeploy'
      - 'Development'
      - 'QA'
      - 'UAT'
      - 'Production'


pool:
  name: VMJMPWA004Agent
  vmImage: VMJMPWA004

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'IMS BuildandDeploy'
    subscriptionId: 'ef49d86b-2dce-461d-abcf-8c307394ad00'
    resourceGroupName: 'rg-core-bd'
    location: 'South Central US'
    csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service.template.json'
    csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service.parameters.json'
