# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  - name: AppServiceName
    type: string
    default: 'certificate-pdf'
    values:
      - 'certificate-pdf'
      - 'ext-user-service'
      - 'ext-user-mgmt'
      - 'vessel-service'
      - 'workorder-service'
      - 'userapi-service'
      - 'vsr-service'
      - 'b2c-cac-service'
      - 'func-b2c'
      - 'func-hkmd'
      - 'func-abspublicrec'
      
  - name: Environment
    type: string
    default: 'BuildandDeploy'
    values:
      - 'BuildandDeploy'
      - 'Development'
      - 'DEV2'
      - 'QA'
      - 'UAT'
      - 'Production'

variables:
   isBuildandDeploy: ${{ eq(parameters.Environment, 'BuildandDeploy') }}
   isDev: ${{ eq(parameters.Environment, 'Development') }}
   isDev2: ${{ eq(parameters.Environment, 'DEV2') }}
   isQA: ${{ eq(parameters.Environment, 'QA') }}
   isUAT: ${{ eq(parameters.Environment, 'UAT') }}
   isProd: ${{ eq(parameters.Environment, 'Production') }}
   
jobs:
  - job: DeployonBuildandDeploy
    condition: and(succeeded(), eq(variables.isBuildandDeploy, 'true'))
    pool: 
      name: VMJMPWA004Agent
      vmImage: VMJMPWA004
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS BuildandDeploy'
          subscriptionId: 'ef49d86b-2dce-461d-abcf-8c307394ad00'
          resourceGroupName: 'rg-core-bd'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'

  - job: DeployonDev
    condition: and(succeeded(), eq(variables.isDev, 'true'))
    pool: 
      name: VMJMPWA001Agent
      vmImage: VMJMPWA001
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
           
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS Development'
          subscriptionId: 'd96bdf11-1497-4091-a786-ca95a185dcba'
          resourceGroupName: 'rg-ffs-dev-001'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'
          
  - job: DeployonDev2
    condition: and(succeeded(), eq(variables.isDev2, 'true'))
    pool: 
      name: VMJMPWA001Agent
      vmImage: VMJMPWA001
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
           
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS Development'
          subscriptionId: 'd96bdf11-1497-4091-a786-ca95a185dcba'
          resourceGroupName: 'rg-ffs-dev-002'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'
          
  - job: DeployonQA
    condition: and(succeeded(), eq(variables.isQA, 'true'))
    pool: 
      name: VMJMPWA003Agent
      vmImage: VMJMPWA003
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
           
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS UAT'
          subscriptionId: '02d0afb7-fc62-4bcf-8215-45a2391a7030'
          resourceGroupName: 'rg-ffs-qa'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'
          
  - job: DeployonUAT
    condition: and(succeeded(), eq(variables.isUAT, 'true'))
    pool: 
      name: VMJMPWA003Agent
      vmImage: VMJMPWA003
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
           
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS UAT'
          subscriptionId: '02d0afb7-fc62-4bcf-8215-45a2391a7030'
          resourceGroupName: 'rg-core-b2c'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'

  - job: DeployonProd
    condition: and(succeeded(), eq(variables.isProd, 'true'))
    pool: 
      name: VMJMPWA005Agent
      vmImage: VMJMPWA005
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          TargetFolder: '$(build.artifactstagingdirectory)'
          CleanTargetFolder: true
           
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'ARM Template deployment: Resource Group scope'
        inputs:
          azureResourceManagerConnection: 'IMS Production'
          subscriptionId: '1e9801a1-93d1-4fd8-98a1-faf8faa915d5'
          resourceGroupName: 'rg-core-b2c'
          location: 'South Central US'
          csmFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.template.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/${{parameters.AppServiceName}}/app-service-${{parameters.Environment}}.parameters.json'
