# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  - name: AppServiceName
    type: string
    default: 'certificate-pdf'
    values:
      - 'certificate-pdf'
      - 'ext-user-service'
      - 'vessel-service'
      - 'workorder-service'


pool:
  name: VMJMPWA004Agent
  vmImage: VMJMPWA004

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'IMS BuildandDeploy'
    subscriptionId: 'ef49d86b-2dce-461d-abcf-8c307394ad00'
    resourceGroupName: 'rg-core-bd'
    location: 'South Central US'
    csmFile: '$(System.DefaultWorkingDirectory)/_svceaglegithub-eagle-org_api-deploy-apim-vs/${{ parameters.AppServiceName}}/app-service.template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/_svceaglegithub-eagle-org_api-deploy-apim-vs/${{ parameters.AppServiceName}}/app-service.parameters.json'
