# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  - name: templateFile
    type: string
    default: 'certificate-pdf/app-service.parameters.json'
    values:
      - 'certificate-pdf/app-service.parameters.json'
      - 'ext-user-service/app-service.parameters.json'
      - 'vessel-service/app-service.parameters.json'
      - 'workorder-service/app-service.parameters.json'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
